name: Delövning 3 - Artifacts

on:
  workflow_dispatch:

jobs:
  create-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Skapar log.txt
        run: # 1. skapa filen
      - name: Laddar upp loggfilen som artifact
        uses: # 2a. vilken action kan användas här?
        # 2b. vad heter denna sektion? 
          name: loggfil
          path: log.txt